[package]
name = "fst-sys"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"

[dependencies]
libz-sys = { version = "1.1.8", features = ["static", "zlib-ng"] }

[build-dependencies]
bindgen = "0.60.1"
cc = "1.0.73"
